apiVersion: v1
kind: Secret
metadata:
  name: borla-backend-secret
  namespace: borla-backend
type: Opaque
stringData:
  DATABASE_URL: 'replace-me'
  JWT_ACCESS_SECRET: 'replace-me'
  JWT_REFRESH_SECRET: 'replace-me'
  ADMIN_PASSWORD: 'replace-me'
  NODEMAILER_HOST_EMAIL: 'replace-me'
  NODEMAILER_HOST_PASS: 'replace-me'
  STRIPE_API_KEY: 'replace-me'
  STRIPE_API_SECRET: 'replace-me'
  PAYSTACK_SECRET_KEY: 'replace-me'
  S3_BUCKET_ACCESS_KEY: 'replace-me'
  S3_BUCKET_SECRET_ACCESS_KEY: 'replace-me'
  AWS_REGION: 'replace-me'
  AWS_BUCKET_NAME: 'replace-me'
  REDIS_URL: 'redis://localhost:6379'
  HUBTEL_POS_ID: 'replace-me'
  HUBTEL_PREPAID_ID: 'replace-me'
  HUBTEL_CLIENT_ID: 'replace-me'
  HUBTEL_CLIENT_SECRET: 'replace-me'
  HUBTEL_SENDER_ID: 'replace-me'
  HUBTEL_API_ID: 'replace-me'
  HUBTEL_API_KEY: 'replace-me'
