apiVersion: v1
kind: Service
metadata:
  name: borla-backend-service
  namespace: borla-backend
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  selector:
    app: borla-backend
  ports:
    - name: http
      port: 5000
      targetPort: http
